"""Build a combined train+validation loader view for the MACE-H trainings.

Why this exists
---------------
`mgo_lr organize` publishes three *separate* loader views (train / validation /
test).  MACE-H's `get_loader()` splits a **single** dataset by ratio, so
pointing a training config at `loader_splits/train` and asking for
`train_ratio = 0.67` re-splits the 330 training snapshots at random and never
looks at the frozen 37-snapshot validation set.  That silently discards the
group-aware split (q-shell + pattern groups) that `organize` computed to keep
related structures out of validation.

The fix is to hand MACE-H one dataset holding train+validation and name the
validation snapshots explicitly through `extra_validation`, with
`train_ratio = 1.0` and `extra_val_test_only = False`.  Then:

    train set = the 330 organize train snapshots, exactly
    val set   = the 37 organize validation snapshots, exactly

and the 37 test snapshots are never loaded at all.

The view is a directory of *real* directories holding file symlinks, mirroring
what `organize._fill_loader_view` produces, because `AijData.process()` walks
with `os.walk`, which does not follow directory symlinks.

Usage
-----
    python -m workflows.training.make_trainval_view [--workspace DIR] [--training-root DIR]

See `workflows/training/paths.py` for how those two locations are resolved.
"""
import os
import shutil
import sys


from workflows.training import paths


def main():
    args = paths.resolved_args(description=__doc__.splitlines()[0])
    workspace, view = args.workspace, paths.trainval_view(args.training_root)

    splits = paths.load_splits(workspace, "main")
    train, val = splits["train"], splits["validation"]
    assert not set(train) & set(val), "train/validation overlap in splits.json"
    assert not set(train) & set(splits["test"]), "train/test overlap"
    assert not set(val) & set(splits["test"]), "validation/test overlap"

    if os.path.exists(view):
        if not os.path.isfile(os.path.join(view, paths.VIEW_MARKER)):
            raise SystemExit(f"{view}: not a view written by this script; "
                             "refusing to replace it")
        shutil.rmtree(view)
    os.makedirs(view)
    with open(os.path.join(view, paths.VIEW_MARKER), "w") as f:
        f.write("generated by workflows/training/make_trainval_view.py\n")

    for subset, sids in (("train", train), ("validation", val)):
        src_root = os.path.join(workspace, "loader_splits", subset)
        for sid in sids:
            src = os.path.join(src_root, sid)
            dst = os.path.join(view, sid)
            os.makedirs(dst)
            for name in sorted(os.listdir(src)):
                # Keep the logical loader-view hop instead of resolving the
                # whole symlink chain.  In particular, hamiltonians.h5 must
                # continue to follow `export-target` when the workspace is
                # switched from SR to full-H.  realpath() pinned this link to
                # hamiltonians_sr.h5 (or hamiltonians_full.h5) forever.
                target = os.path.abspath(os.path.join(src, name))
                if not os.path.exists(target):
                    raise SystemExit(f"{src}/{name} -> {target}: dangling")
                os.symlink(os.path.relpath(target, dst),
                           os.path.join(dst, name))

    # the loader finds a structure by these four files; assert every snapshot
    # in the view is discoverable, and that the count is exactly train+val.
    needed = {"element.dat", "orbital_types.dat", "lat.dat",
              "site_positions.dat"}
    found = [root for root, _, files in os.walk(view)
             if needed.issubset(files)]
    assert len(found) == len(train) + len(val), \
        f"os.walk finds {len(found)}, expected {len(train) + len(val)}"
    print(f"{view}: {len(train)} train + {len(val)} validation "
          f"= {len(found)} discoverable snapshots")
    print("extra_validation = " + repr(sorted(val)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
